### ISSUE TITLE
Ad-Soyad Inputlarına 255 Karakter, Açıklama Inputuna 2048 Karakter Sınırlandırılması

### ISSUE THREAD

**Issue by deniizeynep** [afet-yonetim-sistemi/ays-fe-institution#103]
Ad-Soyad inputlarının karakter sınırlandırılması 255 olarak değiştirilmesi gerekmektedir.

Açıklama inputunun ise karakter sınırlandırılması 2048 olarak değiştirilmesi gerekmektedir.

**Comment by ucsengun** [comment]
@deniizeynep test ettim, herhangi bir bug bulunmamaktadır. Front-End Board'da 'Done' sekmesine ekleyebilirsin.

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/8e0068e5-a6cf-4ebe-aa09-5d53596e1773)
