### ISSUE TITLE
Atamalar Sayfasında Sayfa Başına Görüntülenme Sayısı Değiştirme Hataları

### ISSUE THREAD

**Issue by ucsengun** [afet-yonetim-sistemi/ays-fe-institution#106]
Atamalar sayfasında sayfa başına görüntülenme değiştirildiğinde hata mesajı ile karşılaşılmaktadır.

Sayfa başına 20 görüntülünme seçeneği tıklandığında:

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/7bff792f-3653-4441-bbde-a8739bbea741)

Sayfa başına 50 görüntülenme seçeneği tıklandığında:

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/ed7bf3b7-2f79-4aae-8c4b-b95bb5fb58f3)

Sayfa başına 100 görüntülenme seçeneği tıklandığında:

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/c6c47a96-d69b-46be-92a3-fa893ab8f3ca)

Hata mesajları karşımıza çıkmaktadır.

**Comment by ucsengun** [comment]
@rasitcolakel Sayfa başına görüntülenme seçeneği tek seçenek olup, o seçenek sayfa başına 10 atama görüntülenme sayısıdır.

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/de246e97-6b5e-4c38-81f1-bdcca9ba25ac)

**Comment by rasitcolakel** [comment]
@ucsengun listeleme servisleri sadece 10 gösterimi desteklemekte. Bu sebeple sadece 10 seçeneğini kullanıcıya göstermekteyiz
