### ISSUE TITLE
Fail Olan Pull Requestlerin Check Aşamasının Yeniden Trigger Edilmesi

### ISSUE THREAD

**Issue by ibrahimdenizz** [afet-yonetim-sistemi/ays-fe-institution#123]
Amplify build ayarlarında node versitonun 16 olması nedeniyle şu anda bulunan pull requestler hata veriyor. Bu hataların düzeltilmesi için pull requstlerde bulunan check aşamasının yeniden trigger edilmesi gerekiyor. Aşağıdaki komut kullanılarak boş bir commit ile check aşaması yeniden çalıştırılabilir.

```bash
git commit -m "retrigger checks" --allow-empty
```

## Düzeltilmesi Gereken Pull Requestlerin Issueları
- #116 
- #117 
- #118

**Comment by deniizeynep** [comment]
@ibrahimdenizz, belirtilen issueların pull requestleri için kontrol aşamaları yeniden başlatıldı, teşekkürler.
