### ISSUE TITLE
Yönetici Giriş Sayfası Düzenlemeleri

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-fe-institution#84]
Yönetici Giriş ekranının aşağıdaki maddelere uygun olacak şekilde düzenlenmesi gerekmektedir.

---

### TR
- Component'in içerisinde en üstte ve ortalı olacak şekilde Afet Yönetim Sistemi Logosunun eklenmesi gerekmektedir.
https://i.hizliresim.com/k4huqn1.png
- [x] `Sign in to your account` başlığı yerine `Hoş Geldiniz` başlığı eklenmeli.
- [x] Bu başlığın altına `Lütfen Kullanıcı Adınızı ve Şifrenizi giriniz.` yazmalı.
**Örnek Ekran;**
![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/61833677/04ad1cd0-449b-480b-8d25-2905cc4c937b)
- [x] `Giriş` yerine `Oturum Aç` yazmalı.
- [x] `Parola` yerine `Şifre` yazmalı.

---

### EN
- [x] Component'in içerisinde en üstte ve ortalı olacak şekilde Afet Yönetim Sistemi Logosunun eklenmesi gerekmektedir.
https://i.hizliresim.com/k4huqn1.png
- [x] `Sign in to your account` yazısı yerine `Welcome` yazısı eklenmeli.
- [x]  Bu başlığın altına `Please enter your Username and Password.` yazmalı.
**Örnek Ekran;**
![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/61833677/ec8b1c6d-9f0f-437e-b286-9de0079e6403)

**Comment by ucsengun** [comment]
@rasitcolakel  test ettim, herhangi bir bug bulunmamaktadır. Front-End Board'da 'Done' sekmesine ekleyebilirsin

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/2d4fde3b-07ad-45f1-b26c-b2e03ad1f4d8)


![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/447ea14e-ab65-414a-981d-080ed0643233)

**Comment by rasitcolakel** [comment]
Eline sağlık @ucsengun
