### ISSUE TITLE
Faz 2 - Atama Detay Ekranının Oluşturulması

### ISSUE THREAD

**Issue by kevseroz** [afet-yonetim-sistemi/ays-fe-institution#88]
Faz 2 eklenmesi/geliştirilmesi gereken eklemeler.

- Atanmış bir user bilgisi yoksa koordinatlar kısmının gösterilmemesi.
- iki konum arası oluşturulan çizginin düzenlenip, yol tarifi çizmesi.
- uzakta konum ikonları bozuk görünüyor.
- "Bu konumu google'da aç" seçeneği ekle.

**Comment by ucsengun** [comment]
@kevseroz test ettim, herhangi bir bug bulunmamaktadır. Front-End Board'da 'Done' sekmesine ekleyebilirsin.

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/bbeb6082-515a-46c4-8fa5-9fe11944d7e7)


![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/6b1fd338-dc94-4484-948e-cf62dd7e34cd)



![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/bc399477-2638-47b2-859f-23d105140c25)


![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/4533908b-0bfe-4c6a-8edd-6f9e4f38e3b3)
