### ISSUE TITLE
Atamalar Kısmındaki Bulunan Mevcut Atama Konumunun Yer Belirteci İşaretinin Net Bir Biçimde Gösterilmemesi

### ISSUE THREAD

**Issue by ucsengun** [afet-yonetim-sistemi/ays-fe-institution#91]
Atamalar kısmında yer alan, mevcut atamanın konumu göster butonuna tıkladıktan sonra gelen haritadaki yer belirteci işareti net bir biçimde gösterilmemektedir.
![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/f997561c-e053-4ee6-8b1a-25d2b6a153c5)

**Comment by agitrubard** [comment]
@ucsengun burada görsel görünmüyor, bununla ilgili görseli tekrar ekleyebilir misin?

**Comment by agitrubard** [comment]
Buradaki issue farklı bir geliştirme ile düzeltildiğinden kapatıldı.
