### ISSUE TITLE
Atama Ekleme/Güncelleme Ekranındaki Koordinatların Kullanıcıya Gösterilmemesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-fe-institution#92]
Atama ekleme ve güncelleme ekranlarındaki konum seçme kısmının koordinatları göstermeyecek şekilde güncellenmesi, konum seçildikten sonra küçük bir harita gösterimi içerisinde görünmesi sağlanmalıdır. Koordinatlar elle değiştirilemiyor olmalıdır.

**Comment by agitrubard** [comment]
@rasitcolakel Selamlar,
issue'yu ilerlettikten sonra Projects kısmındaki statüsünü ve label'ini güncelleyebilir miyiz?

**Comment by ucsengun** [comment]
@rasitcolakel Atama ekleme ve güncelleme ekranlarındaki konum seçme kısmının koordinatları göstermeyecek şekildedir. Konum seçildikten sonra küçük bir harita gösterimi içerisinde görüntülenmektedir. Koordinatlar elle değiştirilememektedir.


![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/aeea3ceb-0eed-48ab-a23d-b27ccdfa4e2f)

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/e313b8d5-40c1-4ea0-ac64-e503712cb79f)


![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/22eadf80-65e1-4a7a-92db-f560e5facd68)

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/a43c73b7-38f3-45f0-880b-f7eda385d4d8)

**Comment by rasitcolakel** [comment]
> @rasitcolakel Atama ekleme ve güncelleme ekranlarındaki konum seçme kısmının koordinatları göstermeyecek şekildedir. Konum seçildikten sonra küçük bir harita gösterimi içerisinde görüntülenmektedir. Koordinatlar elle değiştirilememektedir.
> 
> ![image](https://user-images.githubusercontent.com/123711891/279209424-aeea3ceb-0eed-48ab-a23d-b27ccdfa4e2f.png)
> 
> ![image](https://user-images.githubusercontent.com/123711891/279209517-e313b8d5-40c1-4ea0-ac64-e503712cb79f.png)
> 
> ![image](https://user-images.githubusercontent.com/123711891/279208524-22eadf80-65e1-4a7a-92db-f560e5facd68.png)
> 
> ![image](https://user-images.githubusercontent.com/123711891/279208828-a43c73b7-38f3-45f0-880b-f7eda385d4d8.png)

Bu issue'da istenen geliştirme de kullanıcı tarafından elle girilememesi, harita üzerinden seçilmesiydi

**Comment by ucsengun** [comment]
> > @rasitcolakel Atama ekleme ve güncelleme ekranlarındaki konum seçme kısmının koordinatları göstermeyecek şekildedir. Konum seçildikten sonra küçük bir harita gösterimi içerisinde görüntülenmektedir. Koordinatlar elle değiştirilememektedir.
> > ![image](https://user-images.githubusercontent.com/123711891/279209424-aeea3ceb-0eed-48ab-a23d-b27ccdfa4e2f.png)
> > ![image](https://user-images.githubusercontent.com/123711891/279209517-e313b8d5-40c1-4ea0-ac64-e503712cb79f.png)
> > ![image](https://user-images.githubusercontent.com/123711891/279208524-22eadf80-65e1-4a7a-92db-f560e5facd68.png)
> > ![image](https://user-images.githubusercontent.com/123711891/279208828-a43c73b7-38f3-45f0-880b-f7eda385d4d8.png)
> 
> Bu issue'da istenen geliştirme de kullanıcı tarafından elle girilememesi, harita üzerinden seçilmesiydi

@rasitcolakel tam olarak onu yazmıştım orada aslında, elle girilememiştir şeklinde ifade ettim. Herhangi bir bug yok o noktada.
