### ISSUE TITLE
Atamalar Kısmındaki Oluşturulacak Yeni Atama İçin Haritadan Seçim Yaparken Yer Belirteci İşaretinin Net Bir Biçimde Gösterilmemesi 

### ISSUE THREAD

**Issue by ucsengun** [afet-yonetim-sistemi/ays-fe-institution#93]
Atamalar Kısmındaki Oluşturulacak Yeni Atama İçin Haritadan Seçim Yaparken Yer Belirteci İşareti Net Bir Biçimde Gösterilmemektedir. 

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/25d1ebc5-b068-4052-8fab-9b4fb020c9af)

**Comment by deniizeynep** [comment]
Merhaba @ucsengun, ilgili sorunu Brave ve Edge browserlarında test ettim, ben de sorunsuz bir şekilde çalışıyor. Aşağıya da bir örneğini bıraktım. Hangi browserdan test etttiğini öğrenebilir miyim?

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/109898313/30e65784-8767-4879-ac17-f2679d203bb5)

**Comment by ucsengun** [comment]
Merhaba @deniizeynep , chrome browser'ı üzerinden test etmiştim.

**Comment by deniizeynep** [comment]
Chorme ile de test ettim, görselini aşağıya bırakıyorum. Burada da sorunsuz çalışıyor. @ucsengun 

Localimde sorunu tekrarlayamadım sizler de bakar mısınız? @rasitcolakel @kevseroz  

![WhatsApp Image 2023-09-29 at 00 01 54_df03142b](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/109898313/13e12ea4-2a8d-4070-89b1-7531b6175b43)

**Comment by rasitcolakel** [comment]
Selamlar, @deniizeynep ve @ucsengun 

Bu sorun e5f87c5 commiti ile çözülmüştü. Kullandığımız harita paketinin verdiği varsayılan yer işaretinin production ortamında görünmemesi sebebi ile yer işaretlerini değiştirdik
