### ISSUE TITLE
Butonların Daha Test Edilebilir Olması İçin Daha Statik Bir Biçime Dönüştürülmesi

### ISSUE THREAD

**Issue by ucsengun** [afet-yonetim-sistemi/ays-fe-institution#95]
Daha statik hale getirilmesi, butonların işlevselliğini daha iyi test etmelerini sağlar. Örneğin, assignment butonu ile ilgili olarak, dinamik bir şekilde olduğunda bazı featurelarda doğru bir biçimde çalışırken bazı featurelarda net çalışmamaktadır.

**Comment by agitrubard** [comment]
Selamlar @ucsengun,
Toplantı sonrası aldığınız kararla birlikte buraya eklenmesi gereken kısımlarla ilgili detayları da ekleyebilir miyiz?

**Comment by ucsengun** [comment]
Selamlar @agitrubard ,
test idleri atanması noktasında problemler giderilecek alınan kararlara göre.

**Comment by yvzcnr** [comment]
selamlar @agitrubard @ucsengun @rasitcolakel 

[locatorlar ile ilgili son değişiklikler.pptx](https://github.com/afet-yonetim-sistemi/ays-fe-institution/files/13413644/locatorlar.ile.ilgili.son.degisiklikler.pptx)

yansı da belirtilen yerlerin id ataması yapılabilir.

**Comment by agitrubard** [comment]
> selamlar @agitrubard @ucsengun @rasitcolakel
> 
> [locatorlar ile ilgili son değişiklikler.pptx](https://github.com/afet-yonetim-sistemi/ays-fe-institution/files/13413644/locatorlar.ile.ilgili.son.degisiklikler.pptx)
> 
> yansı da belirtilen yerlerin id ataması yapılabilir.

Elinize sağlık 🙌🏼   

@kevseroz @rasitcolakel kontrol ettikten sonra geliştirmelere başlayabilri miyiz?
