### ISSUE TITLE
Atama Açıklaması İki Boşluk Olacak Şekilde Düzenlenmek İstendiğinde 400 Hatası İle Karşılaşılmaktadır

### ISSUE THREAD

**Issue by ucsengun** [afet-yonetim-sistemi/ays-fe-institution#96]
Atama açıklaması iki boşluk olacak şekilde düzenlenmek istendiğinde 400 hatası karşımıza çıkmaktadır.
![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/156452a4-4b14-41eb-9b33-6a2624ca0830)

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/05fb3a84-e0be-47a1-8c8a-f2f830793443)

**Comment by ucsengun** [comment]
@deniizeynep  test ettim, iki boşluk olacak şekilde düzenlenmek istendiğinde, mevcut telefon numarası ile ilgili olarak geçersiz telefon numarası hatası alınmaktadır. 


![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/123711891/3c1b0356-ae61-45fc-b7c3-ae1234cdb8f2)

**Comment by deniizeynep** [comment]
Merhaba @ucsengun, telefon numarasını rastgele sayıları kabul etmeyecek, 5 ile başlama şartı olacak şekilde düzenlemiştim ancak mevcut atamalar bu şekilde kalmış sanırım. Başını 5 ile değiştirdiğimde herhangi bir hata almıyorum. Görseli aşağıya bırakıyorum. 

![image](https://github.com/afet-yonetim-sistemi/ays-fe-institution/assets/109898313/c2a087c4-38ab-4c67-a52c-6b8c26e1018e)
